# Generated by Django 4.2.13 on 2024-06-07 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Outil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=255)),
                ('modele', models.CharField(max_length=255)),
                ('imei', models.CharField(max_length=15, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kada_management.client')),
            ],
        ),
        migrations.CreateModel(
            name='Reparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('outils_utilises', models.ManyToManyField(to='kada_management.outil')),
                ('pannes', models.ManyToManyField(to='kada_management.panne')),
                ('telephone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kada_management.telephone')),
            ],
        ),
        migrations.AddField(
            model_name='panne',
            name='telephone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kada_management.telephone'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reparation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kada_management.reparation')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('micro', models.BooleanField()),
                ('haut_parleur', models.BooleanField()),
                ('systeme_charge', models.BooleanField()),
                ('ecran', models.BooleanField()),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('empreinte', models.BooleanField()),
                ('face_id', models.BooleanField()),
                ('port_sim', models.BooleanField()),
                ('pochette', models.BooleanField()),
                ('reseau', models.BooleanField()),
                ('imei', models.CharField(max_length=15)),
                ('batterie', models.BooleanField()),
                ('boutons_allumage', models.BooleanField()),
                ('boutons_volume', models.BooleanField()),
                ('conver', models.BooleanField()),
                ('torche', models.BooleanField()),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('telephone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kada_management.telephone')),
            ],
        ),
    ]
