# Generated by Django 4.2.13 on 2024-06-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kada_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic',
            name='commentaires',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='diagnostic',
            name='mot_de_passe',
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='is_avant_reparation',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
