# Generated by Django 4.2.13 on 2024-07-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kada_management', '0005_reparation_numero_reparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='numero_fature',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
